<?php 
/**
*	Rubric-Feedback Generator - Verify Form Import
*	 1. outputs the form generated from the submitted tab-delimited text
*
*	@author Jenn Schiffer
*	@version 0.1
*	@package rubric-feedback-generator
*/

if(!isset($_COOKIE["user"])){
	header("Location: index.php");
} else { $username = $_COOKIE["user"]; }

require('includes/header.php'); 

$delimitedText = stripslashes($_POST['delimited-text']);
$delimitedTextItems = explode( '
', $delimitedText );

?>

<body id="process">

	<div id="title-box">
		<h1>Rubric-Feedback Generator</h1>
		<h2>Verify Form Import</h2>
	</div>

	<form id="form-delimited" name="form-delimited" method="post">
		
		<label for="delimited-text">Here is what you entered. You can edit the text to resubmit.</label>
		<em>Clicking the [tab] key will enter a tab in this textarea. To leave this textarea via keyboard shortcut, click [ctrl] key.</em>
		<textarea id="delimited-text" name="delimited-text"><?php echo $delimitedText; ?></textarea>
		
		<input id="submit-form-delimited" type="submit" value="Submit Edits" />
	</form>
	
	
	<p>Here is the form generated by your work. If you change the text above, make sure to click "submit edits" or else those changes will not be reflected below:</p>
	
	<form id="form-output-save" name="form-output-save" method="post">
		
		<div id="form-output">
			<?php processCriteria($delimitedTextItems); ?>
		</div>
		
		<p>Once you've finished generating your form, enter the title and description and save. You can go back and make changes and/or fixes to this rubric later on from the User Admin page.</p>
		
		<input id="form-rubric-content" type="hidden" value="<?php echo $delimitedText; ?>" name="finalDelimitedText" />
		
		<p>
			<label for="form-title">Rubric Title:</label> 
			<input id="form-rubric-title" type="text" name="form-title" />
		</p>
		
		<p>
			<label for="form-description">Rubric Description:</label>
			<textarea id="form-rubric-description" name="form-description"></textarea>
		</p>
		
		<div id="form-save">
			<input id="submit-form-output" class="save" type="submit" value="Save New Rubric" />
		</div>
	
	</form>

<?php require('includes/footer.php'); ?>