<?php 
/**
*	Rubric Creator - Verify Form Import
*	 1. outputs the form generated from the submitted tab-delimited text
*	 2. allows the user to edit the submitted tab-delimited text and resubmit
*	 3. allows the user to verify the rubric generated before moving onto the next step
*
*	@author Jenn Schiffer
*	@version 0.1
*	@package Rubric Creator
*/

require('includes/header.php'); ?>

<body id="process">

<h1>Rubric Creator - Verify Form Import</h1>

<form id="form-delimited" name="form-delimited" action="submit-form.php" method="post">
	<label for="delimited-text">Here is what you entered. You can edit the text to resubmit.</label>
	<textarea name="delimitedtext"><?php echo $delimitedText; ?></textarea>
	<input type="submit" value="submit edits" />
</form>

<p>Here is the form generated by your work:</p>

<form id="form-output">
	<?php processQuestions($delimitedTextItems); ?>
</form>

<?php require('includes/footer.php'); ?>